name: Deploy

on:
  push:
    tags:
      - "v*"
  #    branches:
  #      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Trigger Toolforge deployment
        env:
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          curl --fail-with-body -X POST \
            "https://api.svc.toolforge.org/components/v1/tool/pillbug/deployment?token=${DEPLOYMENT_TOKEN}&force-build=true&force-run=true"
